export const SocketEvents = {
	USER_ONLINE_STATUS_CHANGED: 'USER_ONLINE_STATUS_CHANGED',
	USERID_ONLINE_STATUS_CHANGED: (userId: string) => `USERID_ONLINE_STATUS_CHANGED:${userId}`,
	USER_CREATED: 'USER_CREATED',
	MY_ROOM: (userId: string) => `MY_ROOM:${userId}`,
	MY_USER_LOGGED_IN: 'MY_USER_LOGGED_IN',
	MY_USER_SIGNOUT: 'MY_USER_SIGNOUT',

	ROOM_CREATED: 'ROOM_CREATED',
	ROOM_MESSAGE: 'ROOM_MESSAGE',
	USER_TYPING: 'USER_TYPING',
	MESSAGES_DELETED: 'MESSAGES_DELETED',
	MESSAGE_SEEN: 'MESSAGE_SEEN',

	CREATE_DUET_ROOM: 'CREATE_DUET_ROOM',
	CREATE_GROUP_ROOM: 'CREATE_GROUP_ROOM',
	SEND_MESSAGE: 'SEND_MESSAGE',
	MESSAGE_SEEN_BY_ME: 'MESSAGE_SEEN_BY_ME',
	I_AM_TYPING: 'I_AM_TYPING',
	JOIN_ROOMS: 'JOIN_ROOMS',
	DELETE_MESSAGES: 'DELETE_MESSAGES',

	SET_USER_ONLINE_STATUS: 'SET_USER_ONLINE_STATUS',
};
